version: "3.8"
services:
  forgejo-discord-bot:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    container_name: forgejo-discord-bot
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: forgejo-discord-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: forgejo_discord
      POSTGRES_USER: forgejo_user
      POSTGRES_PASSWORD: forgejo_pass
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: forgejo-discord-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json

volumes:
  postgres_data: